
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { HeartPulse } from "lucide-react";


export default function TermsOfServicePage() {
  return (
    <div className="flex flex-col items-center justify-start min-h-screen bg-background text-foreground">
       {/* Simple Header for this page */}
        <nav className="w-full py-3 bg-card shadow-sm sticky top-0 z-50 border-b">
            <div className="container mx-auto flex items-center justify-between px-4">
                <Link href="/" className="flex items-center space-x-2 text-xl font-bold text-primary hover:opacity-90 transition-opacity">
                    <HeartPulse className="h-6 w-6" />
                    <span>SkinDeep AI</span>
                </Link>
                 <div className="flex space-x-2 items-center">
                    <Button variant="ghost" asChild>
                        <Link href="/" className="text-sm">Home</Link>
                    </Button>
                     <span className="text-muted-foreground/30">|</span>
                     <Button variant="ghost" asChild>
                         <Link href="/awareness" className="text-sm">Skin Conditions</Link>
                     </Button>
                </div>
            </div>
        </nav>

      <main className="container mx-auto px-4 py-12 flex-grow">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
          <p className="mb-4">Last updated: {new Date().toLocaleDateString()}</p>

          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the SkinDeep AI application ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, then you may not access the Service.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-3">2. Description of Service</h2>
            <p>
                SkinDeep AI provides an informational tool that uses artificial intelligence to analyze user-uploaded images or questionnaire responses related to skin conditions. The Service provides potential classifications based on patterns learned from datasets.
            </p>
          </section>

           <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-3">3. No Medical Advice Disclaimer</h2>
            <p className="font-bold text-destructive mb-2">
                IMPORTANT: The Service is for informational purposes only and does not provide medical advice, diagnosis, or treatment.
            </p>
             <p className="mb-2">
                The analysis provided by SkinDeep AI is generated by an AI model and is not a substitute for professional medical evaluation by a qualified healthcare provider, such as a dermatologist. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read or received from this Service.
            </p>
            <p>
                Reliance on any information provided by the Service is solely at your own risk. We do not guarantee the accuracy or completeness of any information provided.
            </p>
          </section>

            <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-3">4. User Responsibilities</h2>
             <ul className="list-disc list-inside space-y-1 ml-4">
                <li>You are responsible for the images and information you provide to the Service. Ensure you have the necessary rights to upload any images.</li>
                <li>You agree not to use the Service for any unlawful purpose or in any way that could damage, disable, overburden, or impair the Service.</li>
                 <li>You understand that the quality of the analysis depends on the quality of the image provided. Clear, well-lit images are recommended.</li>
                <li>You must be 18 years of age or older (or the age of majority in your jurisdiction) to use this Service.</li>
             </ul>
          </section>

            <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-3">5. Intellectual Property</h2>
            <p>
                The Service and its original content (excluding user-provided images and data), features, and functionality are and will remain the exclusive property of SkinDeep AI and its licensors.
            </p>
          </section>

           <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-3">6. Privacy</h2>
            <p>
                Your use of the Service is also governed by our Privacy Policy, which can be found <Link href="/privacy" className="text-primary hover:underline">here</Link>. Please review our Privacy Policy to understand our practices regarding the collection and use of your information.
            </p>
          </section>

            <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-3">7. Limitation of Liability</h2>
            <p>
                In no event shall SkinDeep AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.
            </p>
            <p className="mt-2">
                Our liability is limited to the maximum extent permitted by law. Because the service is provided for informational purposes and does not constitute medical advice, you agree that your use of the service is at your sole risk.
            </p>
          </section>

           <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-3">8. Changes to Terms</h2>
            <p>
               We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">9. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction - e.g., State of California, USA], without regard to its conflict of law provisions.
            </p>
          </section>

            <section className="mt-6">
            <h2 className="text-2xl font-semibold mb-3">10. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at: <Link href="mailto:terms@skindeepai.example.com" className="text-primary hover:underline">terms@skindeepai.example.com</Link>
            </p>
          </section>
        </div>
      </main>

      {/* Footer Section */}
      <footer className="w-full py-8 bg-card text-muted-foreground border-t mt-auto">
        <div className="container mx-auto flex flex-col md:flex-row justify-between items-center px-4 text-center md:text-left">
          <div className="text-xs mb-4 md:mb-0">
            &copy; {new Date().getFullYear()} SkinDeep AI. All Rights Reserved.
          </div>
          <div className="flex space-x-4">
            <Link href="/privacy" className="hover:text-primary text-xs">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-primary text-xs font-semibold">Terms of Service</Link>
            <Link href="mailto:support@skindeepai.example.com" className="hover:text-primary text-xs">Contact Us</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
